github:
  user: "renovate-rancher[bot]"
  email: "119870437+renovate-rancher[bot]@users.noreply.github.com"
  username: "UPDATECLI_GITHUB_ACTOR"
  token: "UPDATECLI_GITHUB_TOKEN"
image:
  bci:
    build:
      name: registry.suse.com/bci/bci-base
      tag: "16.1"
    runtime:
      name: registry.suse.com/bci/bci-minimal
      tag: "16.1"
scm:
  default:
    owner: rancher
    repository: image-build-calico
    branch: master
  upstream:
    owner: projectcalico
    repository: calico
    branch: master
  buildbase:
    owner: rancher
    repository: image-build-base
